name: iOS CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  
jobs:
  build:
    runs-on: macos-latest
    
    env:
      swift: 5.9
      workspace: DodamDodam.xcworkspace
      scheme: DodamDodam
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Tuist
      uses: jdx/mise-action@v2

    - name: Install Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ swift }}
    
    - name: Generate Tuist Workspace
      run: make generate
    
    - name: Build
      run: xcodebuild build \ -workspace $workspace \ -scheme $scheme \ -destination "platform=iOS Simulator,name=iPhone 15 Pro"
